# ── Gemeinsame Einstellungen ──────────────────────────────────
[common]
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.filesystem = littlefs
lib_deps =
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit NeoPixel@^1.12.0

# ── PRODUKT-Board: WaveShare ESP32-S3 Zero ───────────────────
[env:smartsoil_s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = ${common.monitor_speed}
monitor_filters = ${common.monitor_filters}
board_build.filesystem = ${common.board_build.filesystem}
board_build.flash_size = 4MB
upload_speed = 460800
lib_deps = ${common.lib_deps}
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

# ── PROTOTYP-Board: Freenove ESP32-Wrover (zum Testen) ────────
[env:freenove]
platform = espressif32
board = freenove_esp32_wrover
framework = arduino
monitor_speed = ${common.monitor_speed}
monitor_filters = ${common.monitor_filters}
board_build.filesystem = ${common.board_build.filesystem}
upload_port = /dev/cu.usbserial-1430
monitor_port = /dev/cu.usbserial-1430
upload_speed = 460800
lib_deps = ${common.lib_deps}
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DFREENOVE_BOARD
